name: CI/CD - Deploy Model Service

on:
  push:
    branches: [ main ]
    paths:
      - 'model_service/**'

env:
  DOCKER_IMAGE: mhiuuu/parking-model-service 

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./model_service/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            echo "1. Đang kéo (pull) image mới nhất từ Docker Hub..."
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            
            echo "2. Đang dừng và xóa container cũ (nếu có)..."
            docker stop model-service || true
            docker rm model-service || true
            
            echo "3. Đang khởi động container mới..."
            docker run -d -p 5000:5000 --name model-service --network my-network \
            -e MINIO_ENDPOINT=http://minio:9000 \
            -e MINIO_ACCESS_KEY=admin \
            -e MINIO_SECRET_KEY=password \
            -e S3_BUCKET=my-bucket \
            ${{ env.DOCKER_IMAGE }}:latest
            
            echo "4. Deploy hoàn tất!"