# Workflow này chỉ chứa job RESTART.
# Được trigger bởi hàm Lambda (evaluate-promote-trigger)
# sau khi Lambda đã xác nhận mô hình mới tốt hơn và đã promote lên S3.

name: MLOps - Restart Model Service

on:
  repository_dispatch:
    types: [ trigger-restart ]

jobs:
  restart:
    name: Restart Model Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Restart service via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          
          script: |
            echo "Restarting model-service container..."
            docker restart model-service
            echo "Service restarted."

